name: Manual PR Check

on:
  workflow_dispatch: 

jobs:
  pr-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

      - name: Install dependencies with legacy peer deps
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build