name: Manual PR Build Check for React (dev branch)

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request number to check'
        required: true
        type: string

jobs:
  manual-react-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install GitHub CLI and jq
      run: |
        sudo apt update
        sudo apt install -y gh jq

    - name: Authenticate GitHub CLI
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Get PR Info and Validate Target Branch
      id: check-pr
      run: |
        PR_NUMBER=${{ github.event.inputs.pr_number }}
        echo "Checking PR #$PR_NUMBER"
        
        # Set repository context for gh commands
        gh repo set-default ${{ github.repository }}
        
        PR_INFO=$(gh pr view "$PR_NUMBER" --json baseRefName,headRefName,title,number)
        TARGET_BRANCH=$(echo "$PR_INFO" | jq -r .baseRefName)
        SOURCE_BRANCH=$(echo "$PR_INFO" | jq -r .headRefName)
        PR_TITLE=$(echo "$PR_INFO" | jq -r .title)

        echo "PR Title: $PR_TITLE"
        echo "Source branch: $SOURCE_BRANCH"
        echo "Target branch: $TARGET_BRANCH"
        
        if [ "$TARGET_BRANCH" != "dev" ]; then
          echo "❌ This PR does not target the 'dev' branch. Target: $TARGET_BRANCH"
          exit 1
        fi
        echo "✅ PR targets 'dev' branch. Proceeding with build check."

    - name: Checkout PR Code
      run: |
        echo "Fetching and checking out PR #${{ github.event.inputs.pr_number }}"
        gh pr checkout ${{ github.event.inputs.pr_number }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install Dependencies
      run: |
        echo "Installing npm dependencies..."
        npm ci

    - name: Build React App
      run: |
        echo "Building React application..."
        npm run build

    - name: Verify Build Output
      run: |
        echo "Verifying build output..."
        if [ -d "dist" ]; then
          echo "✅ Build directory 'dist' created successfully."
          echo "Build contents:"
          ls -la dist/
        else
          echo "❌ Build failed — 'dist' directory not found."
          echo "Available directories:"
          ls -la
          exit 1
        fi

    - name: Build Summary
      run: |
        echo "🎉 Build check completed successfully for PR #${{ github.event.inputs.pr_number }}"
        echo "✅ Dependencies installed"
        echo "✅ Application built successfully"
        echo "✅ Build artifacts verified"
